### ISSUE TITLE
error in write function

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#116]
# MDF version 3
```python
from mdfreader import mdf, __version__

print(__version__)
mdf(r'test.mdf', noDataLoading=True).write(r'test_write.mdf')
```
```python
2.7.2
Channel t_0_0_0 not in dictionary
Traceback (most recent call last):
  File "D:\TMP\untitled3.py", line 11, in <module>
    mdf(r'd:\PythonWorkspace\asammdf\benchmarks\test.mdf', noDataLoading=True).write(r'd:\PythonWorkspace\asammdf\benchmarks\test_write.mdf')
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 436, in write
    self.convertAllChannel()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 469, in convertAllChannel
    return self._convertAllChannel3()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf3reader.py", line 1032, in _convertAllChannel3
    self.read3(self.fileName, convertAfterRead=True)
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf3reader.py", line 933, in read3
    compression=compression)
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf.py", line 195, in add_channel
    self[channel_name]['conversion'] = {}
KeyError: 't_0_0_0'
```

# MDF version 4
```python
from mdfreader import mdf, __version__

print(__version__)
mdf(r'test.mf4', noDataLoading=True).write(r'test_write.mf4')
```
```python
2.7.2
Channel t_0_0_0 not in dictionary
Traceback (most recent call last):
  File "D:\TMP\untitled3.py", line 11, in <module>
    mdf(r'd:\PythonWorkspace\asammdf\benchmarks\test.mf4', noDataLoading=True).write(r'd:\PythonWorkspace\asammdf\benchmarks\test_write.mf4')
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 436, in write
    self.convertAllChannel()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 471, in convertAllChannel
    return self._convertAllChannel4()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf4reader.py", line 1260, in _convertAllChannel4
    self.read4(self.fileName, convertAfterRead=True)
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf4reader.py", line 1128, in read4
    compression=compression)
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf.py", line 195, in add_channel
    self[channel_name]['conversion'] = {}
KeyError: 't_0_0_0'
```

**Comment by ratal** [comment]
Last commit should fix this issue, thanks for reporting

**Comment by danielhrisca** [comment]
This is fixed, but something similar to issue #92 might have been introduced

**Comment by danielhrisca** [comment]
Hello Aymeric,

I get a new error now:

 ``` python
Save file : mdfreader 2.7.4 noDataLoading mdfv3
<class 'TypeError'>
'NoneType' object is not iterable  File "D:\PythonWorkspace\asammdf\benchmarks\bench.py", line 305, in save_reader3_nodata
    x.write(r'x.mdf')
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 428, in write
    self.convertAllChannel()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 465, in convertAllChannel
    return self._convertAllChannel3()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf3reader.py", line 1053, in _convertAllChannel3
    self.read3(self.fileName, convertAfterRead=True)
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf3reader.py", line 876, in read3
    data_groups = [self[channel][idField][0] for channel in channelList]

Save file : mdfreader 2.7.4 noDataLoading mdfv4
<class 'TypeError'>
'NoneType' object is not iterable  File "D:\PythonWorkspace\asammdf\benchmarks\bench.py", line 335, in save_reader4_nodata
    x.write(r'x.mf4')
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 428, in write
    self.convertAllChannel()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdfreader.py", line 467, in convertAllChannel
    return self._convertAllChannel4()
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf4reader.py", line 1464, in _convertAllChannel4
    self.read4(self.fileName, convertAfterRead=True)
  File "d:\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\mdfreader\mdf4reader.py", line 1212, in read4
    data_groups = [self[channel][idField][0] for channel in channelList]
```

**Comment by ratal** [comment]
Should be fixed in last commit, thanks for pointing out.
I put it in my tests, should not happen again.

**Comment by danielhrisca** [comment]
In the release 2.7.4 there is still a bug when writing mdf version 3 files:

```python
 Save file : mdfreader 2.7.4 noDataLoading mdfv3
<class 'TypeError'>
'NoneType' object is not iterable  File "D:\PythonWorkspace\asammdf\benchmarks\bench.py", line 305, in save_reader3_nodata
    x.write(r'x.mdf')
  File "D:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\mdfreader\mdfreader.py", line 428, in write
    self.convertAllChannel()
  File "D:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\mdfreader\mdfreader.py", line 465, in convertAllChannel
    return self._convertAllChannel3()
  File "D:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\mdfreader\mdf3reader.py", line 1050, in _convertAllChannel3
    self.read3(self.fileName, convertAfterRead=True)
  File "D:\WinPython-32bit-3.6.3.0Qt5\python-3.6.3\lib\site-packages\mdfreader\mdf3reader.py", line 906, in read3
    for channel in channelList]
```

**Comment by ratal** [comment]
Yes, sorry, Daniel, I do not know how I missed it for this release but I already fixed it in last commits.
