### ISSUE TITLE
TypeError when loading MF4 file

### ISSUE THREAD

**Issue by danielhrisca** [ratal/mdfreader#68]
The test file is the same as from issue #67 converted to v4.00 by CANape. 

Environment: Windows 7 x64, WinPython WinPython-32bit-3.5.2.2 and WinPython-32bit-3.6.1.0Qt5, mdfreader 0.2.4

Traceback 
```
Traceback (most recent call last):
  File "E:\02__PythonWorkspace\test.py", line 49, in <module>
    mdfreader4 = MDFreader(r'error.mf4')
  File "E:\02__PythonWorkspace\mdfreader\mdf.py", line 114, in __init__
    self.read(fileName, channelList=channelList, convertAfterRead=convertAfterRead, filterChannelNames=filterChannelNames, multiProc=True)
  File "E:\02__PythonWorkspace\mdfreader\mdfreader.py", line 363, in read
    self.read4(self.fileName, info, multiProc, channelList, convertAfterRead, filterChannelNames=False)
  File "E:\02__PythonWorkspace\mdfreader\mdf4reader.py", line 1362, in read4
    temp.loadInfo(info)  # load all info related to record
  File "E:\02__PythonWorkspace\mdfreader\mdf4reader.py", line 996, in loadInfo
    Channel.set(info, self.dataGroup, self.channelGroup, channelNumber, self.recordIDsize)
  File "E:\02__PythonWorkspace\mdfreader\mdf4reader.py", line 688, in set
    self.desc = self.desc['name']
TypeError: string indices must be integers

```
[error.zip](https://github.com/ratal/mdfreader/files/1144801/error.zip)

**Comment by ratal** [comment]
Hi Daniel,
Last commit should solve this issue, please check and feedback.
Aymeric
